apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
     app: javaapp
     type: front-end
spec:
  template:
     metadata:
       name: javawar-pod
       labels: 
         app: javaapp
         type: front-end
     spec:
         containers:
           - name: tomcatimage
             image: "arjundevsecops/mavenrepo:latest"
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  selector:
    app: javawar
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
      nodePort: 30000
